[package]
name = "kew"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow-array = "53"
arrow-schema = "54"
bach.workspace = true
blake3 = "1"
event-listener-strategy = "0.5"
futures = "0.3"
parquet = "53"
pin-project-lite = "0.2"
xshell = "0.2"
