[book]
authors = ["Cameron Bytheway"]
language = "en"
multilingual = false
src = "target/book"
title = "Kew"

[output.html]
additional-js = ["kew/src/book/vega.js"]
mathjax-support = true

[preprocessor.vega]
