[book]
authors = ["Cameron Bytheway"]
language = "en"
multilingual = false
src = "target/book-src"
title = "Kew"

[build]
build-dir = "target/book"

[output.html]
additional-js = ["kew/src/book/vega.js"]
mathjax-support = true

#[output.pandoc.profile.pdf]
#output-file = "book.pdf"
#to = "latex"

[preprocessor.vega]
