[workspace]
members = ["crates/*", "xtask"]
resolver = "3"

[workspace.dependencies]
# bach = { git = "https://github.com/camshaft/bach" }
bach = { path = "../bach/bach" }
base = { path = "crates/base" }
wasm-bindgen = { version = "=0.2.100" }

[profile.release]
opt-level = "s"
