[package]
name = "kew"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow-array = "53"
arrow-schema = "53"
bach = { path = "../bach/bach" }
blake3 = "1"
duckdb = "1.1.1"
event-listener-strategy = "0.5"
parquet = "53"
pin-project-lite = "0.2"
