[workspace]
members = ["crates/*", "xtask"]
resolver = "3"

[workspace.dependencies]
bach = { version = "0.0.12" }
base = { path = "crates/base" }
wasm-bindgen = { version = "=0.2.100" }

[profile.release]
opt-level = "s"
